services:
  quark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quark-container
    volumes:
      - ./src:/app/src
      - ./includes:/app/includes
    command: ["sleep", "infinity"]