services:
  quark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quark-container
    volumes:
      - ./src:/app/src
      - ./includes:/app/includes
      - ./lint.sh:/app/lint.sh
      - ./CMakeLists.txt:/app/CMakeLists.txt
      - ./main.qrk:/app/main.qrk
    command: ["sleep", "infinity"]
