name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker compose up --build -d
    
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set repository to lowercase
        shell: bash
        run: echo "REPOSITORY=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Push image to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        # Tag with both SHA hash and branch
        run: |
          docker tag $IMAGE ghcr.io/${{ env.REPOSITORY }}/quark:${{ github.sha }}
          docker tag $IMAGE ghcr.io/${{ env.REPOSITORY }}/quark:${{ steps.extract_branch.outputs.branch }}
          docker push ghcr.io/${{ env.REPOSITORY }}/quark:${{ github.sha }}
          docker push ghcr.io/${{ env.REPOSITORY }}/quark:${{ steps.extract_branch.outputs.branch }}

      - name: Stop docker
        run: docker compose down --volumes --rmi all