name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install clang-tidy

      - name: Run Linter
        run: ./lint.sh